spring.application.name=Employee-Management-System

spring.datasource.url=jdbc:mysql://localhost:3306/collegedb
spring.datasource.username=root
spring.datasource.password=Pujitha@6300

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect